### PR TITLE
Upgrade protagonist version

### PR DESCRIPTION
**Pull request by rafaelmenta**
protagonist 0.17.1 is not being installed on latest node version (0.12.2) so I upgraded this dependency to their latest stable version

### CODE REVIEW

**Comment by rafaelmenta** [comment]
Shouldn't it be tested from v0.10?

**Comment by infodark** [comment]
+1

**Comment by ecordell** [comment]
Thanks for updating, and for working out the node dependency. Back when I wrote this protagonist was supporting back to v0.8!

**Comment by rafaelmenta** [comment]
Thank you for the quickness! Are the changes already published on npm?

**Pull request merged**
