### PR TITLE
Update protagonist dependency

### PR DESCRIPTION
**Pull request by Andrew565**
Fixes compatibility of protagonist with Node 5+.

### CODE REVIEW

**Comment by RYFN** [comment]
Would be keen to see this merged in.

**Comment by MartinNuc** [comment]
Any news on this?

**Comment by buob** [comment]
Is this repository no longer maintained?

**Comment by lukerodham** [comment]
Any news on this being done?

**Comment by Andrew565** [comment]
Ancient history.

**Pull request closed without merging**
